### ISSUE TITLE
TypeError: Cannot read property 'lang' of null

### ISSUE THREAD

**Issue by chlab** [eddyerburgh/vue-jest#16]
I am trying out your [webpack template](https://github.com/eddyerburgh/webpack) to use jest for unit testing in a new little app and am getting this error when running `npm run unit`:

```
 FAIL  test/unit/specs/App.spec.js
  ● Test suite failed to run

    TypeError: Cannot read property 'lang' of null

      at processScript (node_modules/jest-vue/lib/process.js:13:17)
      at Object.module.exports [as process] (node_modules/jest-vue/lib/process.js:27:18)
      at Object.<anonymous> (test/unit/specs/App.spec.js:1:114)
```

I reduced the file to an absolute minimum and I'm still getting the error.

App.spec.js
```
import App from '@/App'
```

App.vue
```
<template>
  <div id="app">
  </div>
</template>
```

package.json
```
...
"jest": "^21.2.0",
"jest-vue": "^0.7.0",
...
```

This is the offending line in `jest-vue/lib/process.js`:
```
function processScript (scriptPart) {
  if (scriptPart.lang === 'typescript' || scriptPart.lang === 'ts') {
```
Which seems to make sense since I do not define a `lang` attribute on my script tags.

**Comment by eddyerburgh** [comment]
Hi, thanks for the bug report

I downloaded the webpack repo and failed to reproduce the issue. Would you be able to post the test file and component where you're getting this error, or even better post a reproduction repo?

**Comment by mikemenaker** [comment]
I ran into this issue as well.

I resolved it by changing the function process.js to:

```
function processScript (scriptPart) {
  if(scriptPart != null && scriptPart.hasOwnProperty("lang")) {
    if (scriptPart.lang === 'typescript' || scriptPart.lang === 'ts') {
      return compileTypescript(scriptPart.content)
    }

    if (scriptPart.lang === 'coffee' || scriptPart.lang === 'coffeescript') {
      return compileCoffeeScript(scriptPart.content)
    }

    return compileBabel(scriptPart.content)
  }

  return compileBabel(null)
}
```

**Comment by eddyerburgh** [comment]
I would appreciate a PR, and ideally a unit test with a case that fails. Thanks 🙂

**Comment by mikemenaker** [comment]
Cool, should have something today or tomorrow.

I think this issue popped up because I was using functional SFC with no script section (just a template).

**Comment by mikemenaker** [comment]
Looks like this will handle the issue I ran into:
https://github.com/eddyerburgh/vue-jest/pull/17

Any idea when a new release will go out?

Thanks!

**Comment by eddyerburgh** [comment]
I've just released in 1.0.0 vue-jest.

Note I've changed the package name to vue-jest. You can still download jest-vue, but it won't be receiving further updates.

To install the new version:

```
npm install --save-dev vue-jest
```

I made a request to the original owner of vue-jest to transfer ownership to this repository so that the package name could be more idiomatic to other preprocessors like babel-vue and ts-vue.

**Comment by agualis** [comment]
@mikemenaker I confirm that SFC with no script section do work with version 1.0.0 vue-jest

But **you need to define the template as `<template functional>`**

**Comment by agualis** [comment]
There was another problem when testing nested functional components with mount. This pull request solves the issue:
https://github.com/eddyerburgh/vue-jest/pull/22

**Comment by chlab** [comment]
@eddyerburgh sorry for the late reply.

[This is the repo](https://github.com/chlab/wichteli) that I'm encountering these problems. It has one unit test. I'm no longer seeing the `lang` error, but I'm still seeing the problems [described in the PR](https://github.com/vuejs-templates/webpack/pull/824#issuecomment-338378659).

Do you mind having a quick look? Can you run `npm run unit` without any problems?

Thanks!

**Comment by icaioincau** [comment]
I am having the same problem here :(, the lang one.

**Comment by eddyerburgh** [comment]
@icaioincau is this fixed for you in 1.0.1? If not, can you post the error?

**Comment by agualis** [comment]
Oh! I has oversimplified the parsing of the funcional templates and had forgotten some cases like passing a function or an array as props. 
I just created a new pull request and I hope that this solves most of the common issues but more edge cases should arise so I'll keep an eye on this.  
@eddyerburgh Sorry for the inconvenience, could you run a new release and test it with some complex functional templates please?

**Comment by eddyerburgh** [comment]
I've released the changes in 1.0.2

**Comment by agualis** [comment]
Cool! I have a project with different funcional components and it works. Let's see if we find new edge cases. Thanks for the release!

**Comment by icaioincau** [comment]
Hi @eddyerburgh my components is this: ```<template>
  <section class="error-page__partial">
    <h1 class="error-page__main-title"> {{ $t('i18n.private') }} </h1>
    <h3>Lorem Ipsum at dolor sit amen</h3>
  </section>
</template>
```

He is on a main component that has a script.

```
<template>
  <section class="error-page" :class="modifiers">
    <div>
      <h1 class="error-page__main-title"> {{ $t('i18n.private') }} </h1>
      <h3 v-html="$t('i18n.private')"></h3>
    </div>
    <partial></partial> 
  </section>
</template>
```

The error: 
```

    TypeError: Cannot read property 'lang' of null

      at processScript (node_modules/jest-vue/lib/process.js:13:17)
      at Object.module.exports [as process] (node_modules/jest-vue/lib/process.js:27:18)
      at src/views/ErrorPage/ErrorPage.vue:8:14
      at Object.<anonymous> (src/views/ErrorPage/ErrorPage.vue:106:3)
```

Version used: 1.0.2

**Comment by agualis** [comment]
@icaioincau Try again changing your template to <template functional>...</template>

**Comment by icaioincau** [comment]
It worked :D

**Comment by Ca4tkin** [comment]
Hi! I've still got error with 'lang' in 1.0.2 version. Any way to fix it without adding functional to template?

**Comment by eddyerburgh** [comment]
@Ca4tkin can you post the SFC that you're getting the error with?

**Comment by Ca4tkin** [comment]
@eddyerburgh, here it is:

```
<template>
  <footer class="footer">I'm footer!</footer>
</template>

<style>
.footer {
  padding: 15px;
  border: 1px dashed red;
  text-align: center;
  margin-top: 30px;
}
</style>
```

**Comment by eddyerburgh** [comment]
Thanks for posting the component @Ca4tkin 😀

I've pushed a fix in 1.0.3

**Comment by MaxMilton** [comment]
Thanks @eddyerburgh 1.0.3 fixed the issue in my projects.

**Comment by Ca4tkin** [comment]
@eddyerburgh thanks! It's fixed
